CREATE DATABASE proj_final_mod;

USE proj_final_mod;
 
CREATE TABLE IF NOT EXISTS alunos (
CPF VARCHAR(11) NOT NULL,
NOME VARCHAR(100),
SOBRENOME VARCHAR(150),
DATA_NASCIMENTO DATE,
GENERO VARCHAR(1),
NACIONALIDADE VARCHAR(100),
BAIRRO VARCHAR(100),
CIDADE VARCHAR(100),
ESTADO VARCHAR(100),
PRIMARY KEY (CPF)
);

CREATE TABLE IF NOT EXISTS cursos (
ID_CURSO INT AUTO_INCREMENT,
NOME VARCHAR(100),
DESCRICAO VARCHAR(150),
VALOR FLOAT,
DURACAO_MESES INT,
PRIMARY KEY (ID_CURSO)
);

CREATE TABLE IF NOT EXISTS departamentos (
ID_DEPARTAMENTO INT AUTO_INCREMENT,
NOME VARCHAR(100),
CATEGORIA VARCHAR(50),
PRIMARY KEY (ID_DEPARTAMENTO)
);

CREATE TABLE IF NOT EXISTS cargos (
ID_CARGO INT AUTO_INCREMENT,
NOME VARCHAR(100),
ID_DEPARTAMENTO INT,
DESCRICAO VARCHAR(200),
PRIMARY KEY (ID_CARGO),
FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES departamentos(ID_DEPARTAMENTO)
);

CREATE TABLE IF NOT EXISTS equipe (
MATRICULA INT AUTO_INCREMENT,
CPF VARCHAR(11),
NOME VARCHAR(100),
SOBRENOME VARCHAR(100),
ID_CARGO INT,
DATA_ENTRADA DATE,
DATA_SAIDA DATE,
PRIMARY KEY (MATRICULA),
FOREIGN KEY (ID_CARGO) REFERENCES cargos(ID_CARGO)
);

CREATE TABLE IF NOT EXISTS prof_curso (
INDICE INT AUTO_INCREMENT,
MATRICULA INT,
ID_CURSO INT,
PRIMARY KEY (INDICE),
FOREIGN KEY (MATRICULA) REFERENCES equipe(MATRICULA),
FOREIGN KEY (ID_CURSO) REFERENCES cursos(ID_CURSO)
);

CREATE TABLE IF NOT EXISTS turmas (
ID_TURMA INT AUTO_INCREMENT,
NOME VARCHAR(100),
MATRICULA INT,
ID_CURSO INT,
DATA_INICIO DATE,
DATA_FIM DATE,
PRIMARY KEY (ID_TURMA),
FOREIGN KEY (ID_CURSO) REFERENCES cursos(ID_CURSO),
FOREIGN KEY (MATRICULA) REFERENCES equipe(MATRICULA)
);

CREATE TABLE IF NOT EXISTS inscricoes (
ID_INSCRICAO INT AUTO_INCREMENT,
CPF VARCHAR(11),
ID_TURMA INT,
TIPO_PAGAMENTO VARCHAR(50),
PRIMARY KEY (ID_INSCRICAO),
FOREIGN KEY (CPF) REFERENCES alunos(CPF),
FOREIGN KEY (ID_TURMA) REFERENCES turmas(ID_TURMA),
CHECK (TIPO_PAGAMENTO IN ('A vista debito', 'A vista dinheiro', 'Prazo 6x', 'Prazo 12x'))
);
