CREATE DATABASE proj_final_mod;

CREATE TABLE IF NOT EXISTS alunos (
CPF VARCHAR(11) NOT NULL,
NOME VARCHAR(100),
SOBRENOME VARCHAR(150),
DATA_NASCIMENTO DATE,
GENERO VARCHAR(1),
NACIONALIDADE VARCHAR(100),
BAIRRO VARCHAR(100),
CIDADE VARCHAR(100),
ESTADO VARCHAR(100),
PRIMARY KEY (CPF)
);