use proj_final_mod;

# QUAL A QTD TOTAL DE ESTUDANTES CADASTRADA NO BANCO?
SELECT COUNT(alunos.CPF) AS QTD_ALUNOS FROM alunos;

# QUAIS CURSOS OS ESTUDANTES ESTÃO CADASTRADOS?
SELECT cursos.NOME, alunos.CPF, alunos.NOME FROM
ALUNOS INNER JOIN INSCRICOES
ON alunos.CPF = inscricoes.CPF
INNER JOIN turmas
ON inscricoes.ID_TURMA = turmas.ID_TURMA
INNER JOIN cursos
on turmas.ID_CURSO = cursos.ID_CURSO
GROUP BY alunos.CPF, cursos.ID_CURSO
ORDER BY alunos.NOME;

# QUAL A QUANTIDADE DE TURMAS QUE CADA FACILITADOR ESTÁ ALOCADO?
SELECT equipe.MATRICULA, equipe.NOME, COUNT(*) AS QTD_TURMAS from
turmas inner join equipe
on turmas.MATRICULA = equipe.MATRICULA
where turmas.DATA_FIM > CURDATE() and equipe.DATA_SAIDA is NULL
GROUP BY equipe.MATRICULA
ORDER BY QTD_TURMAS DESC;

# QUAIS CURSOS COM MAIS TURMAS CRIADAS AO LONGO DO ÚLTIMO ANO?
SELECT cursos.NOME, COUNT(turmas.ID_CURSO) AS QTD_TURMAS FROM
turmas INNER JOIN cursos
ON cursos.ID_CURSO = turmas.ID_CURSO
WHERE DATEDIFF(CURDATE(), DATA_INICIO) < 365
GROUP BY turmas.ID_CURSO
ORDER BY QTD_TURMAS DESC;

# QUAL A AVALIAÇÃO MÉDIA DE CADA PROFESSOR?
SELECT tab.NOME_PROF, ROUND(tab.MEDIA_FACILITADOR, 2) AS AVALIACAO_MEDIA,
CASE
	WHEN MEDIA_FACILITADOR >= 8 THEN 'O profe tem boa avaliação'
    WHEN MEDIA_FACILITADOR < 8 AND MEDIA_FACILITADOR > 5 THEN 'O profe possui avaliacao regular'
    WHEN MEDIA_FACILITADOR <= 5 THEN 'O profe possui avaliação ruim'
END AS avaliacao FROM (
	SELECT equipe.NOME AS NOME_PROF, AVG(NOTA_FACILITADOR) AS MEDIA_FACILITADOR FROM
	avaliacoes INNER JOIN turmas
	ON avaliacoes.ID_TURMA = turmas.ID_TURMA
	INNER JOIN equipe
	ON turmas.MATRICULA = equipe.MATRICULA
	GROUP BY turmas.MATRICULA
	ORDER BY MEDIA_FACILITADOR DESC
) tab;

# QUAL A AVALIAÇÃO MÉDIA DE CADA CURSO E A RESPECTIVA CATEGORIZAÇÃO COM MAIOR OCORRÊNCIA?
SELECT NOME_CURSO, AVALIACAO_MEDIA, OPCAO_MAIS_SELECIONADA, MAX(TAB.QTD) AS QTD_OCORRENCIAS,
CASE
	WHEN AVALIACAO_MEDIA >= 8 THEN 'O curso tem boa avaliação'
    WHEN AVALIACAO_MEDIA < 8 AND AVALIACAO_MEDIA > 5 THEN 'O curso possui avaliacao regular'
    WHEN AVALIACAO_MEDIA <= 5 THEN 'O curso possui avaliação ruim'
END AS AVALIACAO FROM (
	SELECT cursos.NOME AS NOME_CURSO, ROUND(AVG(avaliacoes.NOTA_CURSO),2) AS AVALIACAO_MEDIA, avaliacoes.OPCAO_CURSO AS OPCAO_MAIS_SELECIONADA, COUNT(avaliacoes.OPCAO_CURSO) AS QTD FROM
	avaliacoes INNER JOIN turmas
	ON avaliacoes.ID_TURMA = turmas.ID_TURMA
	INNER JOIN cursos
	ON turmas.ID_CURSO = cursos.ID_CURSO
	GROUP BY cursos.ID_CURSO, avaliacoes.OPCAO_CURSO
	ORDER BY cursos.ID_CURSO, QTD DESC
) tab
GROUP BY tab.NOME_CURSO
ORDER BY AVALIACAO_MEDIA DESC;