use proj_final_mod;

# QUAL A QTD TOTAL DE ESTUDANTES CADASTRADA NO BANCO?
SELECT COUNT(alunos.CPF) AS QTD_ALUNOS FROM alunos;

# QUAIS CURSOS OS ESTUDANTES ESTÃO CADASTRADOS?
SELECT cursos.NOME, alunos.CPF, alunos.NOME FROM
ALUNOS INNER JOIN INSCRICOES
ON alunos.CPF = inscricoes.CPF
INNER JOIN turmas
ON inscricoes.ID_TURMA = turmas.ID_TURMA
INNER JOIN cursos
on turmas.ID_CURSO = cursos.ID_CURSO
GROUP BY alunos.CPF, cursos.ID_CURSO
ORDER BY alunos.NOME;

# QUAL A QUANTIDADE DE TURMAS QUE CADA FACILITADOR ESTÁ ALOCADO?
SELECT equipe.MATRICULA, equipe.NOME, COUNT(*) AS QTD_TURMAS from
turmas inner join equipe
on turmas.MATRICULA = equipe.MATRICULA
where turmas.DATA_FIM > CURDATE() and equipe.DATA_SAIDA is NULL
GROUP BY equipe.MATRICULA
ORDER BY QTD_TURMAS DESC;

# QUAIS CURSOS COM MAIS TURMAS CRIADAS AO LONGO DO ÚLTIMO ANO?
SELECT cursos.NOME, COUNT(turmas.ID_CURSO) AS QTD_TURMAS FROM
turmas INNER JOIN cursos
ON cursos.ID_CURSO = turmas.ID_CURSO
WHERE DATEDIFF(CURDATE(), DATA_INICIO) < 365
GROUP BY turmas.ID_CURSO
ORDER BY QTD_TURMAS DESC;